### ISSUE TITLE
Add help

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#30]
I think for this version we should also add a little modal to explain to users how the map is used:

**Contents:**
- What is Babykarte (for)?
- How do I use Babykarte?
- What are the different menu buttons for?
- What do the dots at the markers mean?
- What do the symbols in PDV mean? 

**Things to consider:**
- This has to be small enough to fit onto a regular smartphone screen. If this is not possible, part of the info has to go on a separate page
- There should be a "Don't show again" checkbox (Cookie, maybe a change to Privacy Policy needed)

**Comment by ValorNaram** [comment]
# Representation of help text in language reference files

> What is Babykarte (for)?

A complete short text in the language reference files.

> What are the different menu buttons for?

Referenced like the information in the PDV

> What do the dots at the markers mean?

Referenced like the information in PDV

> What do the symbols in PDV mean?

Referenced like information in PDV

**Comment by ValorNaram** [comment]
> There should be a "Don't show again" checkbox (Cookie, maybe a change to Privacy Policy needed)

Cookies are not needed here.

**Comment by Discostu36** [comment]
I want the modal to open on each visit but with said check box. How can you accomplish that without cookies?

**Comment by ValorNaram** [comment]
What do you mean with __modal__?

**Comment by Discostu36** [comment]
https://www.w3schools.com/howto/howto_css_modals.asp

**Comment by ValorNaram** [comment]
A guided tour or just a legend (a legend is faster than a guided tour and less annoying)?

**Comment by Discostu36** [comment]
I think a short explanation and legend is enough.

**Comment by ValorNaram** [comment]
Perfect and we do not need a cookie because this appears just after the user clicks on the _i_ icon.

**Comment by ValorNaram** [comment]
I commited something, [deployed](https://babykarte.openstreetmap.de/devel) it and I'm not happy about it.

**Comment by Discostu36** [comment]
> I commited something, [deployed](https://babykarte.openstreetmap.de/devel) it and I'm not happy about it.

Don't see anything 

![Screenshot_20191122-193717_Firefox](https://user-images.githubusercontent.com/30999326/69451398-8dc87400-0d5f-11ea-8a4d-df6a0fb64c3d.jpg)

**Comment by Discostu36** [comment]
> Perfect and we do not need a cookie because this appears just after the user clicks on the _i_ icon.

That's the thing. I'd like the help to be displayed on first visit.

**Comment by ValorNaram** [comment]
### I do not use Cookies and here is why:

- Cookies are intransparent technology
- Mainstream society does not know much about this technology and does not care about it.
- Mainstream society didn't want the GDPR to happen because of lack of awareness. (Meaning I need to protect them)
  - They didn't get the idea of taking control back of their own data.
- GDPR is not accepted by me because it puts responsibility in the hand of the providers (Customers literally drop the responsibility) but I obey it.  (Meaning I need to protect the Mainstream society).
  - People need to be self-conscious and self-aware and this is currently lacking.
- People are not aware of the great power of the WWW and the great responsibility coming with it.

### Solution

I'm willing to reconsider my point of view, if Mainstream also reconsider their beliefs. The first step needs to be done by Mainstream society, they need to prove to me that they're ready for this. As long as they do not get out of their bubble, as long I need to protect them from outer world.

### Solution for our situation

I changed the text shown in the overlay showing up when no filter has been selected (On initiation of Babykarte by navigating to its location on the internet) to also pinpoint to the help section.

**Comment by ValorNaram** [comment]
**[Deployment](https://babykarte.openstreetmap.de/devel) synchronized.**

**Comment by Discostu36** [comment]
Thanks. I'll shorten the text a bit.

**Comment by ValorNaram** [comment]
I think I found a good solution that doesn't get me on my nerves because I'm one of the internet users who set their Browser to forget website data (including history and cookies) on closing.

Everytime I use iD for the first time in current session I need to click the prompt for the tutorial away.

**Comment by Discostu36** [comment]
I've shortened the text a bit. Still missing is an explanation of the baby friendliness icons in PDV.

**Comment by ValorNaram** [comment]
**Added**, could you look throw and do necessary shortenings because our help is to long and still not really good. Feel free also to improve the mobile layout via CSS.

**Comment by ValorNaram** [comment]
**Please take also a look throw the english translation.**

**Comment by Discostu36** [comment]
Last thing to do for the help in my opinion:

Please have the same two column layouts for the PDV icons as for the menu icons
![grafik](https://user-images.githubusercontent.com/30999326/69901027-cd084d80-137b-11ea-8f99-57f03fa5ff81.png)
