### ISSUE TITLE
Also show playgroud features that are mapped as linestring feature

### ISSUE THREAD

**Issue by patzi** [babykarte/babykarte#45]
As far as I can see playground features that are mapped as a way/line or are/polygon are not shown on the map. If you don't want the map to show them as line/polygon you could use the centroid.

Examples for features not mapped as a point:
way: https://www.openstreetmap.org/way/566960842
area: https://www.openstreetmap.org/way/762081843

Map position
https://babykarte.openstreetmap.de/#19&54.3425&10.1370
https://babykarte.openstreetmap.de/devel/#19&54.3425&10.1370

**Comment by ValorNaram** [comment]
Hi and welcome,

thanks for mapping a playground. I clicked the links and then activated the filter and Babykarte shew me the necessary data. You might have not waited one hour before looking how Babykarte represents your data. Our database is one hour behind the offcial OpenStreetMap one you upload to. In issue #42 we're working on an explanation about this update delay.

**Comment by patzi** [comment]
OK, I see the are feature is included, didn't wait long enough, sorry. But the line feature https://www.openstreetmap.org/way/566960842 not, it is also not a new mapped one. So it seems only line features are missing.
Thanks for the map ;)

**Comment by ValorNaram** [comment]
> But the line feature https://www.openstreetmap.org/way/566960842 not, it is also not a new mapped one.

This object is not in our database. The queries did not find anything related to the object

    select * from osm_poi_poly where tags->'manufacturer'='Junior Spielplatzgeräte GmbH';
    select * from osm_poi_poly where osm_id=566960842;
    select * from osm_poi_poly where osm_id=-566960842;

To verify that our database contains objects tagged with `playground=structure` I ran the following query:

     select * from osm_poi_poly where tags->'playground'='structure' limit 1;

which gave me following result:

id    |osm_id             |tags                                                                                                                                                                                                       |geom                                                                                                                                                                                                                                                           |
------|-------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
124115|-100000000006402350|"name"=>"Fort Trappenkamp", "type"=>"multipolygon", "building"=>"yes", "playground"=>"structure", "roof:shape"=>"gabled", "roof:material"=>"tar_paper", "building:levels"=>"2", "building:material"=>"wood"|POLYGON ((10.23683498439371 54.02545368225168, 10.237128853918989 54.02553423234119, 10.237262126179445 54.025366426639636, 10.236968256654166 54.02528587655016, 10.23683498439371 54.02545368225168), (10.236894747363351 54.025435828797924, 10.236984266089|

meaning 'Yes, our database contains objects tagged like this and logically also all objects having the `playground` Key.

BUT I know that not all OpenStreetMap objects (only those we need) are being imported in our database to save resources. I modified the query from above to show me 10 results instead of just one. And in the list of ten items I saw one just tagged with `playground=structure`:

id    |osm_id             |tags                                                                                                                                                                                                                                                           |geom                                                                                                                                                                                                                                                           |
------|-------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
492046|          -33536305|"playground"=>"structure"                                                                                                                                                                                                                                      |POLYGON ((11.35291154348505 44.53894424886289, 11.35323424675721 44.538955229156045, 11.35352275186446 44.53896394633534, 11.35354957395461 44.5389643654305, 11.353569774341253 44.53863613010225, 11.35357748569217 44.53850998245946, 11.353311360266417 44.|

So our filter cannot be the problem.

**Comment by ValorNaram** [comment]
Our filter just let the importer import those elements containing one or more key in our whitelist.

**Comment by patzi** [comment]
You tried to find it in your polygon table but the osm way https://www.openstreetmap.org/way/566960842 should be a linestring feature
> > But the line feature https://www.openstreetmap.org/way/566960842 not, it is also not a new mapped one.
> 
> This object is not in our database. The queries did not find anything related to the object
> 
> ```
> select * from osm_poi_poly where tags->'manufacturer'='Junior Spielplatzgeräte GmbH';
> select * from osm_poi_poly where osm_id=566960842;
> select * from osm_poi_poly where osm_id=-566960842;
> ```
As far as i can see you don't have any linestring geometries in your db only point and polygons or am I wrong? I tried to have a look at the backend as well but could find anything linestring related.

**Comment by ValorNaram** [comment]
>  I tried to have a look at the backend as well but could find anything linestring related.

The backend does not contain the database configuration because it does not belong to Babykarte. But the table `osm_poi_poly` contains Ways, Areas and Relationens so it must be there. Apparently it isn't. I will wait and see, if it's a temporary issue or not.

**Comment by ValorNaram** [comment]
Seems to be a database issue https://github.com/giggls/osmpoidb/blob/master/poi-only.yml

**Comment by ValorNaram** [comment]
We're working on it but first we need to validate the new data the database we want to contain in near future.

**Comment by ValorNaram** [comment]
Both versions of Babykarte [living](https://babykarte.openstreetmap.de/) and [devel](https://babykarte.openstreetmap.de/devel) now include playground equipment mapped as linestring features (linear open way). The DB and the [backend](https://github.com/babykarte/backend) have been updated accordingly.
