### ISSUE TITLE
POI rating system

### ISSUE THREAD

**Issue by Discostu36** [babykarte/babykarte#50]
ValorNaram and I have already talked about this but it is not documented yet.

I'd like to have a rating system for restaurants and cafes. If they are baby friendly (e.g. have highchairs and a changing table), the marker should have a green glow. If they are only partially baby friendly, it should be yellow, if not at all, red. If there is not enought data, there should be no glow at all.

@ValorNaram Can you share the first draft of the rating system we agreed on? I don't have it in my notes and would like to work on it.

**Comment by ValorNaram** [comment]
> One possibility would be to work with green and red points:

Possible with positive (green) and negative (red) points (integers):

Green: 9 points or more
Yellow: 8 points or less but not less than 0
Red: 0 points or less

**Example 1:**
diaper= yes (+8 points)
highchair = no (-8 points)
stroller= no data
kids_area= no data
0 points --> yellow

**Example 2:**
diaper=no (-8 points)
highchair=no data
stroller=no data
kids_area= no data
-8 points --> No color because `countabletag  >= 2` is not true

**Example 3:**
diaper=no (-8 points)
highchair=no (-8 points)
stroller = yes (+3 points)
kids_area=no (-4 points)
-17 points --> red

**Example 4:**
diaper=yes (+8 points)
highchair=yes (+8 points)
stroller = limited (+1 points)
kids_area=no (-4 points)
13 points --> green

> I'm still struggeling with the problem that I'd like to show red colour only when there is enough data available.

Activate rating system when at least two tags can be analysed. `countabletag >= 2`

@Discostu36 please comment on this.

**Comment by ValorNaram** [comment]
@Discostu36 and I phoned yesterday and I told him from my plan to move functions Babykarte exposes with its Frontend to its Backend. That means: The amount lines of code decreases for the Frontend and increases for the Backend. More will be done on the server side and with this development we're breaking Babykarte's tradition to be written mostly in Javascript. The [devel version](https://babykarte.openstreetmap.de/devel) also allows the display of POI's which do not expose Babykarte's purpose. This way we allow other user groups (other than parents) to use Babykarte.

We're aware of the COVID-19 crisis and this is cutting down our traffic but we see it as a chance to think about ways to make Babykarte even more beautiful and to wait with the release. At the end of the crisis we will be happy to great you with a new version of Babykarte. But until then we will be busy improving it :-)

**Comment by bjwo** [comment]
Hi, please include the key changing_table in your calculation. diaper seems to be deprecated. Thanks.

**Comment by ValorNaram** [comment]
We were the ones who created `Key:changing_table` and therefore fully support this scheme but also the deprecated `diaper` one (legacy support).

**Comment by bjwo** [comment]
Perfect - I just assumed it wasn't, because it's described differently in the documentation: https://wiki.openstreetmap.org/wiki/Babykarte#Bewertungssystem

**Comment by ValorNaram** [comment]
That's the old algorithm. We use a new one which I needed to develop since the old was a barrier for moving some jobs over to the Backend.

[This comment](https://github.com/babykarte/babykarte/issues/50#issuecomment-611750252) describes that new algorithm.

**Comment by ValorNaram** [comment]
And the wiki is out of date. I need to link that section to that issue comment.
